# Generated by Django 4.0.7 on 2022-10-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_something_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_secretary',
            field=models.BooleanField(default=False, help_text='If its true this is a secretary', verbose_name='secretary'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False, help_text='If its true this is a student', verbose_name='student'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(default=False, help_text='If its true this is a teacher', verbose_name='teacher'),
        ),
    ]
