# Generated by Django 4.0.7 on 2022-10-03 16:09

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_secretary_user_is_student_user_is_teacher'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.CustomUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_secretary',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_teacher',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('SECRETARY', 'Secretary'), ('MANAGER', 'Manager')], default='MANAGER', max_length=200),
            preserve_default=False,
        ),
    ]
