# Generated by Django 4.0.7 on 2022-10-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IBAN', models.CharField(max_length=50, verbose_name='IBAN')),
                ('name', models.CharField(max_length=500, verbose_name='Company name')),
                ('color_first', models.CharField(max_length=50, verbose_name='Primary Color')),
                ('color_secondary', models.CharField(max_length=50, verbose_name='Secondary Color')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('SECRETARY', 'Secretary'), ('MANAGER', 'Manager'), ('OWNER', 'Owner')], max_length=200),
        ),
    ]
