# Generated by Django 4.0.7 on 2022-10-04 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='holded_id',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
