# Generated by Django 4.0.7 on 2022-10-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_holded_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='holded_api_key',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Holded api key'),
        ),
    ]
