# Generated by Django 4.0.7 on 2022-10-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_created_user_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='extra_field',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
