# Generated by Django 4.0.8 on 2022-10-06 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('users', '0017_secretaryprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secretaryprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='SecretaryProfile',
        ),
        migrations.DeleteModel(
            name='TeacherProfile',
        ),
    ]
