# Generated by Django 4.0.8 on 2022-10-12 15:36

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0024_alter_user_offices"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(default="Las Palmas de GC", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="color",
            field=models.CharField(default="#FFFFFF", max_length=200),
        ),
        migrations.AddField(
            model_name="user",
            name="dni",
            field=models.CharField(default="45368103M", max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+34677609928",
                max_length=128,
                region=None,
                verbose_name="phone_number",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="postal_code",
            field=models.CharField(default="35014", max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="province",
            field=models.CharField(default="Las Palmas", max_length=200),
            preserve_default=False,
        ),
    ]
