# Generated by Django 4.0.8 on 2022-10-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_user_city_user_color_user_dni_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='Paseo de chil 167', max_length=500),
            preserve_default=False,
        ),
    ]
