# Generated by Django 4.0.7 on 2022-09-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
