# Generated by Django 4.0.7 on 2022-10-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0002_alter_office_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='extra_field',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
