# Generated by Django 4.0.7 on 2022-10-01 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('licences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='Modified at')),
                ('thumbnail', models.ImageField(upload_to='')),
                ('brand', models.CharField(blank=True, max_length=400, null=True)),
                ('model', models.CharField(blank=True, max_length=400, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('plate_number', models.CharField(max_length=200, unique=True)),
                ('bastidor_number', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('state', models.CharField(choices=[('USING', 'using'), ('FIXING', 'fixing'), ('STANDING', 'standing')], default='USING', max_length=200)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('fuel_type', models.CharField(choices=[('USING', 'using'), ('FIXING', 'fixing'), ('STANDING', 'standing')], max_length=300)),
                ('itv_date', models.DateField(blank=True, null=True)),
                ('consumption_per_litter', models.FloatField(blank=True, null=True)),
                ('ficha_tecnica', models.FileField(blank=True, null=True, upload_to='pdf')),
                ('permiso_circulacion', models.FileField(blank=True, null=True, upload_to='pdf')),
                ('seguro', models.FileField(blank=True, null=True, upload_to='pdf')),
                ('licences', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='licences.license')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
