# Generated by Django 4.0.7 on 2022-10-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('CICLOMOTOR', 'CICLOMOTOR'), ('MOTORBIKE', 'MOTORBIKE'), ('TURISMO', 'TURISMO'), ('CAMION', 'CAMION')], max_length=300),
        ),
    ]
