# Generated by Django 4.0.7 on 2022-10-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_vehicle_fuel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('GAS', 'Gasolina'), ('DIE', 'Diesel'), ('ELE', 'Eléctrico'), ('HYB', 'Hibrído')], max_length=400, null=True),
        ),
    ]
