# Generated by Django 4.0.7 on 2022-10-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_alter_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('CICLOMOTOR', 'Ciclomotor'), ('MOTORBIKE', 'Motocicleta'), ('TURISMO', 'Turismo'), ('CAMION', 'Camión')], max_length=300),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='state',
            field=models.CharField(choices=[('USING', 'Usandose'), ('FIXING', 'Reparandose'), ('STANDING', 'En reserva')], default='USING', max_length=200),
        ),
    ]
