# Generated by Django 4.0.7 on 2022-10-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_alter_vehicle_fuel_type_alter_vehicle_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('GAS', 'Gasolina'), ('DIE', 'Diesel'), ('ELE', 'Eléctrico'), ('HYB', 'Hibrído')], max_length=300),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('CICLOMOTOR', 'Ciclomotor'), ('MOTORBIKE', 'Motocicleta'), ('TURISMO', 'Turismo'), ('CAMION', 'Camión')], max_length=400, null=True),
        ),
    ]
