# Generated by Django 4.0.7 on 2022-10-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_alter_vehicle_fuel_type_alter_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='extra_field',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
