# Generated by Django 4.0.8 on 2022-10-09 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
        ('vehicles', '0009_alter_vehicle_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_vehicles', to='teachers.teacherprofile'),
        ),
    ]
