# Generated by Django 4.0.8 on 2022-10-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_alter_vehicle_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='name',
            field=models.CharField(default='Peugeout 308', max_length=200),
            preserve_default=False,
        ),
    ]
