# Generated by Django 4.0.8 on 2022-10-14 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dgt_name', models.CharField(choices=[('AM', 'AM'), ('A1', 'A1'), ('A2', 'A2'), ('A', 'A'), ('B', 'B')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PermissionClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissions.permission')),
            ],
        ),
    ]
