# Generated by Django 4.0.8 on 2022-10-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='friday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='friday_finish',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='friday_start',
            field=models.TimeField(default='8:00'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='monday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='monday_finish',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='monday_start',
            field=models.TimeField(default='8:00'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='saturday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='saturday_finish',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='saturday_start',
            field=models.TimeField(default='8:00'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='sunday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='sunday_finish',
            field=models.TimeField(default='13:00'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='sunday_start',
            field=models.TimeField(default='8:00'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='thursday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='thursday_finish',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='thursday_start',
            field=models.TimeField(default='8:00'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='tuesday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='tuesday_finish',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='tuesday_start',
            field=models.TimeField(default='8:00'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='wednesday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='wednesday_finish',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='wednesday_start',
            field=models.TimeField(default='8:00'),
        ),
    ]
