# Generated by Django 4.0.8 on 2022-10-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacherprofile_friday_teacherprofile_friday_finish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='calendar_frame',
            field=models.IntegerField(default=45),
        ),
    ]
