# Generated by Django 4.0.7 on 2022-09-21 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseModel',
        ),
        migrations.DeleteModel(
            name='ReceiverModel',
        ),
    ]
